//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffWeb.UI.MVC.fPeerLendingServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="fPeerLendingServiceReference.IMobileService")]
    public interface IMobileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/MakeBorrowOffer", ReplyAction="http://tempuri.org/IMobileService/MakeBorrowOfferResponse")]
        fPeerLending.Entities.Offer MakeBorrowOffer(fPeerLending.Entities.OfferModel offerModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/MakeBorrowOffer", ReplyAction="http://tempuri.org/IMobileService/MakeBorrowOfferResponse")]
        System.Threading.Tasks.Task<fPeerLending.Entities.Offer> MakeBorrowOfferAsync(fPeerLending.Entities.OfferModel offerModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/MakeLendOffer", ReplyAction="http://tempuri.org/IMobileService/MakeLendOfferResponse")]
        fPeerLending.Entities.Offer MakeLendOffer(fPeerLending.Entities.OfferModel offerModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/MakeLendOffer", ReplyAction="http://tempuri.org/IMobileService/MakeLendOfferResponse")]
        System.Threading.Tasks.Task<fPeerLending.Entities.Offer> MakeLendOfferAsync(fPeerLending.Entities.OfferModel offerModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/GetOfferById", ReplyAction="http://tempuri.org/IMobileService/GetOfferByIdResponse")]
        fPeerLending.Entities.Offer GetOfferById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/GetOfferById", ReplyAction="http://tempuri.org/IMobileService/GetOfferByIdResponse")]
        System.Threading.Tasks.Task<fPeerLending.Entities.Offer> GetOfferByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/GetOffers", ReplyAction="http://tempuri.org/IMobileService/GetOffersResponse")]
        fPeerLending.Entities.Offer[] GetOffers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileService/GetOffers", ReplyAction="http://tempuri.org/IMobileService/GetOffersResponse")]
        System.Threading.Tasks.Task<fPeerLending.Entities.Offer[]> GetOffersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMobileServiceChannel : ffWeb.UI.MVC.fPeerLendingServiceReference.IMobileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MobileServiceClient : System.ServiceModel.ClientBase<ffWeb.UI.MVC.fPeerLendingServiceReference.IMobileService>, ffWeb.UI.MVC.fPeerLendingServiceReference.IMobileService {
        
        public MobileServiceClient() {
        }
        
        public MobileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public fPeerLending.Entities.Offer MakeBorrowOffer(fPeerLending.Entities.OfferModel offerModel) {
            return base.Channel.MakeBorrowOffer(offerModel);
        }
        
        public System.Threading.Tasks.Task<fPeerLending.Entities.Offer> MakeBorrowOfferAsync(fPeerLending.Entities.OfferModel offerModel) {
            return base.Channel.MakeBorrowOfferAsync(offerModel);
        }
        
        public fPeerLending.Entities.Offer MakeLendOffer(fPeerLending.Entities.OfferModel offerModel) {
            return base.Channel.MakeLendOffer(offerModel);
        }
        
        public System.Threading.Tasks.Task<fPeerLending.Entities.Offer> MakeLendOfferAsync(fPeerLending.Entities.OfferModel offerModel) {
            return base.Channel.MakeLendOfferAsync(offerModel);
        }
        
        public fPeerLending.Entities.Offer GetOfferById(int Id) {
            return base.Channel.GetOfferById(Id);
        }
        
        public System.Threading.Tasks.Task<fPeerLending.Entities.Offer> GetOfferByIdAsync(int Id) {
            return base.Channel.GetOfferByIdAsync(Id);
        }
        
        public fPeerLending.Entities.Offer[] GetOffers() {
            return base.Channel.GetOffers();
        }
        
        public System.Threading.Tasks.Task<fPeerLending.Entities.Offer[]> GetOffersAsync() {
            return base.Channel.GetOffersAsync();
        }
    }
}
