//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:24:16 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace ffWeb.UI.MVC.Models
{
    /// <summary>
    /// Represents a row of spUser data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class spUser_Model
    {
        /// <summary>
        /// Gets or sets a int value for the Id column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets a int value for the RoleId column.
        /// </summary>
        [DataMember]
        public int RoleId { get; set; }

        /// <summary>
        /// Gets or sets a string value for the UserName column.
        /// </summary>
        [DataMember]
        public string UserName { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Password column.
        /// </summary>
        [DataMember]
        public string Password { get; set; }
         [DataMember]
        public string password_hash { get; set; } 
        [DataMember]
        public string password_salt { get; set; }
         
        /// <summary>
        /// Gets or sets a string value for the Status column.
        /// </summary>
        [DataMember]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the Locked column.
        /// </summary>
        [DataMember]
        public bool Locked { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsDeleted column.
        /// </summary>
        [DataMember]
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Gets or sets a string value for the SystemId column.
        /// </summary>
        [DataMember]
        public string SystemId { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Surname column.
        /// </summary>
        [DataMember]
        public string Surname { get; set; }

        /// <summary>
        /// Gets or sets a string value for the OtherNames column.
        /// </summary>
        [DataMember]
        public string OtherNames { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the DateOfBirth column.
        /// </summary>
        [DataMember]
        public DateTime DateOfBirth { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Gender column.
        /// </summary>
        [DataMember]
        public string Gender { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Telephone column.
        /// </summary>
        [DataMember]
        public string Telephone { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Email column.
        /// </summary>
        [DataMember]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the DateJoined column.
        /// </summary>
        [DataMember]
        public DateTime DateJoined { get; set; }

        /// <summary>
        /// Gets or sets a string value for the InformBy column.
        /// </summary>
        [DataMember]
        public string InformBy { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Photo column.
        /// </summary>
        [DataMember]
        public string Photo { get; set; }

        /// <summary>
        /// Gets or sets a string value for the NationalID column.
        /// </summary>
        [DataMember]
        public string NationalID { get; set; }
    }
}
