//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffWeb.UI.MVC.GeneralLedgerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GeneralLedgerServiceReference.IStaticTransactionsService")]
    public interface IStaticTransactionsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/AvailableBalance", ReplyAction="http://tempuri.org/IStaticTransactionsService/AvailableBalanceResponse")]
        decimal AvailableBalance(fanikiwaGL.Entities.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/AvailableBalance", ReplyAction="http://tempuri.org/IStaticTransactionsService/AvailableBalanceResponse")]
        System.Threading.Tasks.Task<decimal> AvailableBalanceAsync(fanikiwaGL.Entities.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAvailableBalance", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAvailableBalanceResponse")]
        decimal GetAvailableBalance(int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAvailableBalance", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAvailableBalanceResponse")]
        System.Threading.Tasks.Task<decimal> GetAvailableBalanceAsync(int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAccountLimitAmount", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAccountLimitAmountResponse")]
        decimal GetAccountLimitAmount(int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAccountLimitAmount", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAccountLimitAmountResponse")]
        System.Threading.Tasks.Task<decimal> GetAccountLimitAmountAsync(int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/BlockFunds", ReplyAction="http://tempuri.org/IStaticTransactionsService/BlockFundsResponse")]
        void BlockFunds(fanikiwaGL.Entities.Account account, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/BlockFunds", ReplyAction="http://tempuri.org/IStaticTransactionsService/BlockFundsResponse")]
        System.Threading.Tasks.Task BlockFundsAsync(fanikiwaGL.Entities.Account account, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/ClearEffects", ReplyAction="http://tempuri.org/IStaticTransactionsService/ClearEffectsResponse")]
        void ClearEffects(fanikiwaGL.Entities.Account account, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/ClearEffects", ReplyAction="http://tempuri.org/IStaticTransactionsService/ClearEffectsResponse")]
        System.Threading.Tasks.Task ClearEffectsAsync(fanikiwaGL.Entities.Account account, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/CloseAccount", ReplyAction="http://tempuri.org/IStaticTransactionsService/CloseAccountResponse")]
        void CloseAccount(fanikiwaGL.Entities.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/CloseAccount", ReplyAction="http://tempuri.org/IStaticTransactionsService/CloseAccountResponse")]
        System.Threading.Tasks.Task CloseAccountAsync(fanikiwaGL.Entities.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/CreateCustomer", ReplyAction="http://tempuri.org/IStaticTransactionsService/CreateCustomerResponse")]
        fanikiwaGL.Entities.Customer CreateCustomer(fanikiwaGL.Entities.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/CreateCustomer", ReplyAction="http://tempuri.org/IStaticTransactionsService/CreateCustomerResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.Customer> CreateCustomerAsync(fanikiwaGL.Entities.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAccount", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAccountResponse")]
        fanikiwaGL.Entities.Account GetAccount(int accountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAccount", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAccountResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.Account> GetAccountAsync(int accountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAccountLimitStatus", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAccountLimitStatusResponse")]
        fanikiwaGL.Framework.AccountLimitStatus GetAccountLimitStatus(fanikiwaGL.Entities.Account act);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAccountLimitStatus", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAccountLimitStatusResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Framework.AccountLimitStatus> GetAccountLimitStatusAsync(fanikiwaGL.Entities.Account act);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAccountLockStatus", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAccountLockStatusResponse")]
        fanikiwaGL.Framework.PassFlag GetAccountLockStatus(fanikiwaGL.Entities.Account act);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAccountLockStatus", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAccountLockStatusResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Framework.PassFlag> GetAccountLockStatusAsync(fanikiwaGL.Entities.Account act);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAccountTransactionsByDate", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAccountTransactionsByDateRespons" +
            "e")]
        fanikiwaGL.Entities.Transaction[] GetAccountTransactionsByDate(int accountId, System.DateTime startDate, System.DateTime endtDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAccountTransactionsByDate", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAccountTransactionsByDateRespons" +
            "e")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.Transaction[]> GetAccountTransactionsByDateAsync(int accountId, System.DateTime startDate, System.DateTime endtDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetCustomerByEmail", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetCustomerByEmailResponse")]
        fanikiwaGL.Entities.Customer GetCustomerByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetCustomerByEmail", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetCustomerByEmailResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.Customer> GetCustomerByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetCustomerByID", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetCustomerByIDResponse")]
        fanikiwaGL.Entities.Customer GetCustomerByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetCustomerByID", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetCustomerByIDResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.Customer> GetCustomerByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/MarkLimit", ReplyAction="http://tempuri.org/IStaticTransactionsService/MarkLimitResponse")]
        void MarkLimit(fanikiwaGL.Entities.Account account, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/MarkLimit", ReplyAction="http://tempuri.org/IStaticTransactionsService/MarkLimitResponse")]
        System.Threading.Tasks.Task MarkLimitAsync(fanikiwaGL.Entities.Account account, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/OpenAccount", ReplyAction="http://tempuri.org/IStaticTransactionsService/OpenAccountResponse")]
        fanikiwaGL.Entities.Account OpenAccount(fanikiwaGL.Entities.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/OpenAccount", ReplyAction="http://tempuri.org/IStaticTransactionsService/OpenAccountResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.Account> OpenAccountAsync(fanikiwaGL.Entities.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/SetAccountLimitStatus", ReplyAction="http://tempuri.org/IStaticTransactionsService/SetAccountLimitStatusResponse")]
        void SetAccountLimitStatus(fanikiwaGL.Entities.Account acc, fanikiwaGL.Framework.AccountLimitStatus status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/SetAccountLimitStatus", ReplyAction="http://tempuri.org/IStaticTransactionsService/SetAccountLimitStatusResponse")]
        System.Threading.Tasks.Task SetAccountLimitStatusAsync(fanikiwaGL.Entities.Account acc, fanikiwaGL.Framework.AccountLimitStatus status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/SetAccountLockStatus", ReplyAction="http://tempuri.org/IStaticTransactionsService/SetAccountLockStatusResponse")]
        void SetAccountLockStatus(fanikiwaGL.Entities.Account acc, fanikiwaGL.Framework.PassFlag status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/SetAccountLockStatus", ReplyAction="http://tempuri.org/IStaticTransactionsService/SetAccountLockStatusResponse")]
        System.Threading.Tasks.Task SetAccountLockStatusAsync(fanikiwaGL.Entities.Account acc, fanikiwaGL.Framework.PassFlag status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/UnBlockFunds", ReplyAction="http://tempuri.org/IStaticTransactionsService/UnBlockFundsResponse")]
        void UnBlockFunds(fanikiwaGL.Entities.Account account, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/UnBlockFunds", ReplyAction="http://tempuri.org/IStaticTransactionsService/UnBlockFundsResponse")]
        System.Threading.Tasks.Task UnBlockFundsAsync(fanikiwaGL.Entities.Account account, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/UpdateAccount", ReplyAction="http://tempuri.org/IStaticTransactionsService/UpdateAccountResponse")]
        void UpdateAccount(fanikiwaGL.Entities.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/UpdateAccount", ReplyAction="http://tempuri.org/IStaticTransactionsService/UpdateAccountResponse")]
        System.Threading.Tasks.Task UpdateAccountAsync(fanikiwaGL.Entities.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/UpdateCustomer", ReplyAction="http://tempuri.org/IStaticTransactionsService/UpdateCustomerResponse")]
        fanikiwaGL.Entities.Customer UpdateCustomer(fanikiwaGL.Entities.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/UpdateCustomer", ReplyAction="http://tempuri.org/IStaticTransactionsService/UpdateCustomerResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.Customer> UpdateCustomerAsync(fanikiwaGL.Entities.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAllAccounts", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAllAccountsResponse")]
        fanikiwaGL.Entities.Account[] GetAllAccounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAllAccounts", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAllAccountsResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.Account[]> GetAllAccountsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetOpenAccounts", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetOpenAccountsResponse")]
        fanikiwaGL.Entities.Account[] GetOpenAccounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetOpenAccounts", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetOpenAccountsResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.Account[]> GetOpenAccountsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetClosedAccounts", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetClosedAccountsResponse")]
        fanikiwaGL.Entities.Account[] GetClosedAccounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetClosedAccounts", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetClosedAccountsResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.Account[]> GetClosedAccountsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAllTransactionTypes", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAllTransactionTypesResponse")]
        fanikiwaGL.Entities.TransactionType[] GetAllTransactionTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAllTransactionTypes", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAllTransactionTypesResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.TransactionType[]> GetAllTransactionTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetTransactionType", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetTransactionTypeResponse")]
        fanikiwaGL.Entities.TransactionType GetTransactionType(int transactiontypeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetTransactionType", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetTransactionTypeResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.TransactionType> GetTransactionTypeAsync(int transactiontypeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetTieredTable", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetTieredTableResponse")]
        fanikiwaGL.Entities.TieredDet[] GetTieredTable(int tieredID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetTieredTable", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetTieredTableResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.TieredDet[]> GetTieredTableAsync(int tieredID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/IsAccountClosed", ReplyAction="http://tempuri.org/IStaticTransactionsService/IsAccountClosedResponse")]
        bool IsAccountClosed(int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/IsAccountClosed", ReplyAction="http://tempuri.org/IStaticTransactionsService/IsAccountClosedResponse")]
        System.Threading.Tasks.Task<bool> IsAccountClosedAsync(int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAllTransactions", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAllTransactionsResponse")]
        fanikiwaGL.Entities.Transaction[] GetAllTransactions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAllTransactions", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAllTransactionsResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.Transaction[]> GetAllTransactionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAccountTransactions", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAccountTransactionsResponse")]
        fanikiwaGL.Entities.Transaction[] GetAccountTransactions(int _accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAccountTransactions", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAccountTransactionsResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.Transaction[]> GetAccountTransactionsAsync(int _accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAllCustomers", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAllCustomersResponse")]
        fanikiwaGL.Entities.Customer[] GetAllCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAllCustomers", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAllCustomersResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.Customer[]> GetAllCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAccountViewTransactionsByDate", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAccountViewTransactionsByDateRes" +
            "ponse")]
        fanikiwaGL.Entities.TransactionModel[] GetAccountViewTransactionsByDate(int accountId, System.DateTime startDate, System.DateTime endtDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/GetAccountViewTransactionsByDate", ReplyAction="http://tempuri.org/IStaticTransactionsService/GetAccountViewTransactionsByDateRes" +
            "ponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.TransactionModel[]> GetAccountViewTransactionsByDateAsync(int accountId, System.DateTime startDate, System.DateTime endtDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/CreateTransactionType", ReplyAction="http://tempuri.org/IStaticTransactionsService/CreateTransactionTypeResponse")]
        fanikiwaGL.Entities.TransactionType CreateTransactionType(fanikiwaGL.Entities.TransactionType TransactionType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/CreateTransactionType", ReplyAction="http://tempuri.org/IStaticTransactionsService/CreateTransactionTypeResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.TransactionType> CreateTransactionTypeAsync(fanikiwaGL.Entities.TransactionType TransactionType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/UpdateTransactionType", ReplyAction="http://tempuri.org/IStaticTransactionsService/UpdateTransactionTypeResponse")]
        fanikiwaGL.Entities.TransactionType UpdateTransactionType(fanikiwaGL.Entities.TransactionType TransactionType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/UpdateTransactionType", ReplyAction="http://tempuri.org/IStaticTransactionsService/UpdateTransactionTypeResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.TransactionType> UpdateTransactionTypeAsync(fanikiwaGL.Entities.TransactionType TransactionType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/AccountExists", ReplyAction="http://tempuri.org/IStaticTransactionsService/AccountExistsResponse")]
        bool AccountExists(int account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/AccountExists", ReplyAction="http://tempuri.org/IStaticTransactionsService/AccountExistsResponse")]
        System.Threading.Tasks.Task<bool> AccountExistsAsync(int account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/SelectLastTranscations", ReplyAction="http://tempuri.org/IStaticTransactionsService/SelectLastTranscationsResponse")]
        fanikiwaGL.Entities.Transaction[] SelectLastTranscations(int accountID, int Take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/SelectLastTranscations", ReplyAction="http://tempuri.org/IStaticTransactionsService/SelectLastTranscationsResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.Transaction[]> SelectLastTranscationsAsync(int accountID, int Take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/SelectByAccountDateRange", ReplyAction="http://tempuri.org/IStaticTransactionsService/SelectByAccountDateRangeResponse")]
        fanikiwaGL.Entities.Transaction[] SelectByAccountDateRange(int accountID, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaticTransactionsService/SelectByAccountDateRange", ReplyAction="http://tempuri.org/IStaticTransactionsService/SelectByAccountDateRangeResponse")]
        System.Threading.Tasks.Task<fanikiwaGL.Entities.Transaction[]> SelectByAccountDateRangeAsync(int accountID, System.DateTime startDate, System.DateTime endDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStaticTransactionsServiceChannel : ffWeb.UI.MVC.GeneralLedgerServiceReference.IStaticTransactionsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StaticTransactionsServiceClient : System.ServiceModel.ClientBase<ffWeb.UI.MVC.GeneralLedgerServiceReference.IStaticTransactionsService>, ffWeb.UI.MVC.GeneralLedgerServiceReference.IStaticTransactionsService {
        
        public StaticTransactionsServiceClient() {
        }
        
        public StaticTransactionsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StaticTransactionsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaticTransactionsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaticTransactionsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal AvailableBalance(fanikiwaGL.Entities.Account account) {
            return base.Channel.AvailableBalance(account);
        }
        
        public System.Threading.Tasks.Task<decimal> AvailableBalanceAsync(fanikiwaGL.Entities.Account account) {
            return base.Channel.AvailableBalanceAsync(account);
        }
        
        public decimal GetAvailableBalance(int accountid) {
            return base.Channel.GetAvailableBalance(accountid);
        }
        
        public System.Threading.Tasks.Task<decimal> GetAvailableBalanceAsync(int accountid) {
            return base.Channel.GetAvailableBalanceAsync(accountid);
        }
        
        public decimal GetAccountLimitAmount(int accountid) {
            return base.Channel.GetAccountLimitAmount(accountid);
        }
        
        public System.Threading.Tasks.Task<decimal> GetAccountLimitAmountAsync(int accountid) {
            return base.Channel.GetAccountLimitAmountAsync(accountid);
        }
        
        public void BlockFunds(fanikiwaGL.Entities.Account account, decimal amount) {
            base.Channel.BlockFunds(account, amount);
        }
        
        public System.Threading.Tasks.Task BlockFundsAsync(fanikiwaGL.Entities.Account account, decimal amount) {
            return base.Channel.BlockFundsAsync(account, amount);
        }
        
        public void ClearEffects(fanikiwaGL.Entities.Account account, decimal amount) {
            base.Channel.ClearEffects(account, amount);
        }
        
        public System.Threading.Tasks.Task ClearEffectsAsync(fanikiwaGL.Entities.Account account, decimal amount) {
            return base.Channel.ClearEffectsAsync(account, amount);
        }
        
        public void CloseAccount(fanikiwaGL.Entities.Account account) {
            base.Channel.CloseAccount(account);
        }
        
        public System.Threading.Tasks.Task CloseAccountAsync(fanikiwaGL.Entities.Account account) {
            return base.Channel.CloseAccountAsync(account);
        }
        
        public fanikiwaGL.Entities.Customer CreateCustomer(fanikiwaGL.Entities.Customer customer) {
            return base.Channel.CreateCustomer(customer);
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.Customer> CreateCustomerAsync(fanikiwaGL.Entities.Customer customer) {
            return base.Channel.CreateCustomerAsync(customer);
        }
        
        public fanikiwaGL.Entities.Account GetAccount(int accountID) {
            return base.Channel.GetAccount(accountID);
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.Account> GetAccountAsync(int accountID) {
            return base.Channel.GetAccountAsync(accountID);
        }
        
        public fanikiwaGL.Framework.AccountLimitStatus GetAccountLimitStatus(fanikiwaGL.Entities.Account act) {
            return base.Channel.GetAccountLimitStatus(act);
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Framework.AccountLimitStatus> GetAccountLimitStatusAsync(fanikiwaGL.Entities.Account act) {
            return base.Channel.GetAccountLimitStatusAsync(act);
        }
        
        public fanikiwaGL.Framework.PassFlag GetAccountLockStatus(fanikiwaGL.Entities.Account act) {
            return base.Channel.GetAccountLockStatus(act);
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Framework.PassFlag> GetAccountLockStatusAsync(fanikiwaGL.Entities.Account act) {
            return base.Channel.GetAccountLockStatusAsync(act);
        }
        
        public fanikiwaGL.Entities.Transaction[] GetAccountTransactionsByDate(int accountId, System.DateTime startDate, System.DateTime endtDate) {
            return base.Channel.GetAccountTransactionsByDate(accountId, startDate, endtDate);
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.Transaction[]> GetAccountTransactionsByDateAsync(int accountId, System.DateTime startDate, System.DateTime endtDate) {
            return base.Channel.GetAccountTransactionsByDateAsync(accountId, startDate, endtDate);
        }
        
        public fanikiwaGL.Entities.Customer GetCustomerByEmail(string email) {
            return base.Channel.GetCustomerByEmail(email);
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.Customer> GetCustomerByEmailAsync(string email) {
            return base.Channel.GetCustomerByEmailAsync(email);
        }
        
        public fanikiwaGL.Entities.Customer GetCustomerByID(int id) {
            return base.Channel.GetCustomerByID(id);
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.Customer> GetCustomerByIDAsync(int id) {
            return base.Channel.GetCustomerByIDAsync(id);
        }
        
        public void MarkLimit(fanikiwaGL.Entities.Account account, decimal amount) {
            base.Channel.MarkLimit(account, amount);
        }
        
        public System.Threading.Tasks.Task MarkLimitAsync(fanikiwaGL.Entities.Account account, decimal amount) {
            return base.Channel.MarkLimitAsync(account, amount);
        }
        
        public fanikiwaGL.Entities.Account OpenAccount(fanikiwaGL.Entities.Account account) {
            return base.Channel.OpenAccount(account);
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.Account> OpenAccountAsync(fanikiwaGL.Entities.Account account) {
            return base.Channel.OpenAccountAsync(account);
        }
        
        public void SetAccountLimitStatus(fanikiwaGL.Entities.Account acc, fanikiwaGL.Framework.AccountLimitStatus status) {
            base.Channel.SetAccountLimitStatus(acc, status);
        }
        
        public System.Threading.Tasks.Task SetAccountLimitStatusAsync(fanikiwaGL.Entities.Account acc, fanikiwaGL.Framework.AccountLimitStatus status) {
            return base.Channel.SetAccountLimitStatusAsync(acc, status);
        }
        
        public void SetAccountLockStatus(fanikiwaGL.Entities.Account acc, fanikiwaGL.Framework.PassFlag status) {
            base.Channel.SetAccountLockStatus(acc, status);
        }
        
        public System.Threading.Tasks.Task SetAccountLockStatusAsync(fanikiwaGL.Entities.Account acc, fanikiwaGL.Framework.PassFlag status) {
            return base.Channel.SetAccountLockStatusAsync(acc, status);
        }
        
        public void UnBlockFunds(fanikiwaGL.Entities.Account account, decimal amount) {
            base.Channel.UnBlockFunds(account, amount);
        }
        
        public System.Threading.Tasks.Task UnBlockFundsAsync(fanikiwaGL.Entities.Account account, decimal amount) {
            return base.Channel.UnBlockFundsAsync(account, amount);
        }
        
        public void UpdateAccount(fanikiwaGL.Entities.Account account) {
            base.Channel.UpdateAccount(account);
        }
        
        public System.Threading.Tasks.Task UpdateAccountAsync(fanikiwaGL.Entities.Account account) {
            return base.Channel.UpdateAccountAsync(account);
        }
        
        public fanikiwaGL.Entities.Customer UpdateCustomer(fanikiwaGL.Entities.Customer customer) {
            return base.Channel.UpdateCustomer(customer);
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.Customer> UpdateCustomerAsync(fanikiwaGL.Entities.Customer customer) {
            return base.Channel.UpdateCustomerAsync(customer);
        }
        
        public fanikiwaGL.Entities.Account[] GetAllAccounts() {
            return base.Channel.GetAllAccounts();
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.Account[]> GetAllAccountsAsync() {
            return base.Channel.GetAllAccountsAsync();
        }
        
        public fanikiwaGL.Entities.Account[] GetOpenAccounts() {
            return base.Channel.GetOpenAccounts();
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.Account[]> GetOpenAccountsAsync() {
            return base.Channel.GetOpenAccountsAsync();
        }
        
        public fanikiwaGL.Entities.Account[] GetClosedAccounts() {
            return base.Channel.GetClosedAccounts();
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.Account[]> GetClosedAccountsAsync() {
            return base.Channel.GetClosedAccountsAsync();
        }
        
        public fanikiwaGL.Entities.TransactionType[] GetAllTransactionTypes() {
            return base.Channel.GetAllTransactionTypes();
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.TransactionType[]> GetAllTransactionTypesAsync() {
            return base.Channel.GetAllTransactionTypesAsync();
        }
        
        public fanikiwaGL.Entities.TransactionType GetTransactionType(int transactiontypeid) {
            return base.Channel.GetTransactionType(transactiontypeid);
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.TransactionType> GetTransactionTypeAsync(int transactiontypeid) {
            return base.Channel.GetTransactionTypeAsync(transactiontypeid);
        }
        
        public fanikiwaGL.Entities.TieredDet[] GetTieredTable(int tieredID) {
            return base.Channel.GetTieredTable(tieredID);
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.TieredDet[]> GetTieredTableAsync(int tieredID) {
            return base.Channel.GetTieredTableAsync(tieredID);
        }
        
        public bool IsAccountClosed(int accountid) {
            return base.Channel.IsAccountClosed(accountid);
        }
        
        public System.Threading.Tasks.Task<bool> IsAccountClosedAsync(int accountid) {
            return base.Channel.IsAccountClosedAsync(accountid);
        }
        
        public fanikiwaGL.Entities.Transaction[] GetAllTransactions() {
            return base.Channel.GetAllTransactions();
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.Transaction[]> GetAllTransactionsAsync() {
            return base.Channel.GetAllTransactionsAsync();
        }
        
        public fanikiwaGL.Entities.Transaction[] GetAccountTransactions(int _accountid) {
            return base.Channel.GetAccountTransactions(_accountid);
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.Transaction[]> GetAccountTransactionsAsync(int _accountid) {
            return base.Channel.GetAccountTransactionsAsync(_accountid);
        }
        
        public fanikiwaGL.Entities.Customer[] GetAllCustomers() {
            return base.Channel.GetAllCustomers();
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.Customer[]> GetAllCustomersAsync() {
            return base.Channel.GetAllCustomersAsync();
        }
        
        public fanikiwaGL.Entities.TransactionModel[] GetAccountViewTransactionsByDate(int accountId, System.DateTime startDate, System.DateTime endtDate) {
            return base.Channel.GetAccountViewTransactionsByDate(accountId, startDate, endtDate);
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.TransactionModel[]> GetAccountViewTransactionsByDateAsync(int accountId, System.DateTime startDate, System.DateTime endtDate) {
            return base.Channel.GetAccountViewTransactionsByDateAsync(accountId, startDate, endtDate);
        }
        
        public fanikiwaGL.Entities.TransactionType CreateTransactionType(fanikiwaGL.Entities.TransactionType TransactionType) {
            return base.Channel.CreateTransactionType(TransactionType);
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.TransactionType> CreateTransactionTypeAsync(fanikiwaGL.Entities.TransactionType TransactionType) {
            return base.Channel.CreateTransactionTypeAsync(TransactionType);
        }
        
        public fanikiwaGL.Entities.TransactionType UpdateTransactionType(fanikiwaGL.Entities.TransactionType TransactionType) {
            return base.Channel.UpdateTransactionType(TransactionType);
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.TransactionType> UpdateTransactionTypeAsync(fanikiwaGL.Entities.TransactionType TransactionType) {
            return base.Channel.UpdateTransactionTypeAsync(TransactionType);
        }
        
        public bool AccountExists(int account) {
            return base.Channel.AccountExists(account);
        }
        
        public System.Threading.Tasks.Task<bool> AccountExistsAsync(int account) {
            return base.Channel.AccountExistsAsync(account);
        }
        
        public fanikiwaGL.Entities.Transaction[] SelectLastTranscations(int accountID, int Take) {
            return base.Channel.SelectLastTranscations(accountID, Take);
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.Transaction[]> SelectLastTranscationsAsync(int accountID, int Take) {
            return base.Channel.SelectLastTranscationsAsync(accountID, Take);
        }
        
        public fanikiwaGL.Entities.Transaction[] SelectByAccountDateRange(int accountID, System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.SelectByAccountDateRange(accountID, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<fanikiwaGL.Entities.Transaction[]> SelectByAccountDateRangeAsync(int accountID, System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.SelectByAccountDateRangeAsync(accountID, startDate, endDate);
        }
    }
}
